"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { Provider } from "react-redux";
import { store } from "@/lib/reduxStore";
import { MdMenu } from "react-icons/md";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sets, setSets] = useState<{ id: string; title: string }[] | null>(
    null
  );
  const router = useRouter();
  const params = useParams();
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [sidebarWidthPct, setSidebarWidthPct] = useState(25); // percentage of viewport
  const isDragging = useRef(false);

  // Gets the sets when the page loads or when the id changes
  useEffect( () => {
    async function fetchSets() {
      try {
        const response = await fetch(
          `${process.env.NEXT_PUBLIC_BASE_URL}/api/queue-card/fetchSets`,
          {
            method: "POST",
          }
        );
        const data = await response.json();
        setSets(data.sets);
      } catch (error) {
        console.error("Error fetching card sets:", error);
      }
    }
    
    fetchSets();
  }, [params.id]);

  async function deleteSet() {
    if (!params.id) return;

    const confirmDelete = confirm("Are you sure you want to delete this set?");
    if (!confirmDelete) return;

    try {
      const response = await fetch(
        `${process.env.NEXT_PUBLIC_BASE_URL}/api/queue-card/deleteSet`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ id: params.id }),
        }
      );
      const data = await response.json();
      if (data.success) {
        // Remove the deleted set from state
        setSets((prevSets) =>
          prevSets ? prevSets.filter((set) => set.id !== params.id) : null
        );
        router.push("/app");
      }
    } catch (error) {
      console.error("Error deleting card set:", error);
    }
  }

  return (
    <div className="relative flex h-viewport lg:h-screen flex-col lg:flex-row justify-between gap-3 duration-200">
      <div className="absolute top-0 left-0 z-50 lg:hidden">
        <MdMenu
          className="w-12 h-12 pt-2 pl-2 cursor-pointer"
          onClick={() => {
            console.log(sidebarOpen);
            setSidebarOpen((open) => !open);
          }}
        />
      </div>
      {/* Invisible bar to close the sidebar */}
      <div
        className={`lg:hidden fixed inset-0 z-10 transition-all duration-300 ease-in-out ${
          sidebarOpen
            ? "opacity-100 backdrop-blur-sm pointer-events-auto"
            : "opacity-0 backdrop-blur-none pointer-events-none"
        }`}
        onClick={() => setSidebarOpen(false)}
      ></div>
      {/* Mobile Side Bar */}
      <div
        className={`lg:hidden absolute top-0 left-0 w-[70%] h-screen bg-black/80 flex flex-col rounded-lg p-8 max-w-2xl z-20 transition-transform duration-300 ease-in-out ${
          sidebarOpen ? "translate-x-0" : "-translate-x-full"
        }`}
      >
        <Sidebar sets={sets} deleteSet={deleteSet} params={params} />
      </div>

      {/* Desktop Side Bar */}
      <div
        className={`hidden lg:flex absolute left-0 top-0 h-full z-10 flex-col bg-black/30 rounded-lg p-8 transition-transform duration-300 ease-in-out ${
          !sidebarOpen ? "lg:translate-x-0" : "lg:-translate-x-full"
        }`}
        style={{ width: `${sidebarWidthPct}%` }}
      >
        <Sidebar sets={sets} deleteSet={deleteSet} params={params} />

        {/* Drag handle */}
        <div
          className="bg-gray-200 w-fit h-fit absolute top-1/2 -translate-y-1/2 -translate-x-1/2 left-full rounded-full cursor-col-resize select-none"
          onClick={() => {
            if (!isDragging.current) setSidebarOpen((open) => !open);
          }}
          onMouseDown={(e) => {
            e.preventDefault();
            isDragging.current = false;

            const startX = e.clientX;
            const startWidth = sidebarWidthPct;

            const onMouseMove = (moveEvent: MouseEvent) => {
              const delta = moveEvent.clientX - startX;
              if (Math.abs(delta) > 3) isDragging.current = true;
              const newPct = startWidth + (delta / window.innerWidth) * 100;
              setSidebarWidthPct(Math.min(Math.max(newPct, 10), 40));
            };

            const onMouseUp = () => {
              window.removeEventListener("mousemove", onMouseMove);
              window.removeEventListener("mouseup", onMouseUp);
            };

            window.addEventListener("mousemove", onMouseMove);
            window.addEventListener("mouseup", onMouseUp);
          }}
        >
          <MdMenu className="rotate-90 text-black w-5 h-5 p-1" />
        </div>
      </div>
      {/* Desktop Side Bar Flex Placeholder */}
      <div
        className={`hidden lg:block transition-all duration-300 ease-in-out overflow-hidden ${
          sidebarOpen ? "w-0" : ""
        }`}
        style={{ width: sidebarOpen ? 0 : `${sidebarWidthPct}%` }}
      ></div>

      <Provider store={store}>
        <div className="flex-1">{children}</div>
      </Provider>
    </div>
  );
}

function Sidebar({
  sets,
  deleteSet,
  params,
}: {
  sets: { id: string; title: string }[] | null;
  deleteSet: () => void;
  params: { id?: string | string[] };
}) {
  return (
    <>
      <h1 className="text-4xl font-bold mb-4">QueCard</h1>

      <div className="flex flex-col gap-2">
        <Link
          href="/app"
          className={`px-4 py-2 rounded hover:bg-gray-900 cursor-pointer text-left ${
            !params?.id && "bg-gray-800"
          }`}
        >
          Create New Book
        </Link>

        <h2>Books</h2>
        <div className="flex flex-col gap-1">
          {sets &&
            sets.map((set) => (
                <Link key={set.id} href={`/app/${set.id}`}>
              <div
                className={`rounded cursor-pointer flex justify-between items-center gap-2 px-4 py-2 ${
                  params?.id === set.id && "bg-gray-800"
                }`}
              >
                <h3 className="m-0 overflow-hidden text-ellipsis">{set.title}</h3>
                <button
                  className={`${
                    params?.id === set.id
                      ? "bg-gray-900 cursor-pointer"
                      : "hidden"
                  }`}
                  onClick={deleteSet}
                >
                  Delete
                </button>
              </div>
                </Link>
            ))}
        </div>
      </div>
    </>
  );
}
