"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { Provider } from "react-redux";
import { store } from "@/lib/reduxStore";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sets, setSets] = useState<{ id: string; title: string }[] | null>(
    null
  );
  const loading = useRef(false);
  const params = useParams();

  useEffect(() => {
    if (loading.current || sets !== null) return;
    loading.current = true;

    async function fetchSets() {
      try {
        const response = await fetch(
          `${process.env.NEXT_PUBLIC_BASE_URL}/api/queue-card/fetchSets`,
          {
            method: "POST",
          }
        );
        const data = await response.json();
        setSets(data.sets);
      } catch (error) {
        console.error("Error fetching card sets:", error);
      }
    }

    fetchSets();
  }, [sets]);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-screen max-h-screen">
          <main className="flex min-h-screen flex-row justify-between gap-6">
            {/* Side Bar */}
            <div className="flex flex-col bg-black/30 rounded-lg p-8">
              <h1 className="text-4xl font-bold mb-4">QueCard</h1>

              <div className="flex flex-col gap-2">
                <Link
                  href="/"
                  className={`px-4 py-2 rounded hover:bg-gray-900 cursor-pointer text-left ${
                    !params.id && "bg-gray-800"
                  }`}
                >
                  Create New Flashcards
                </Link>

                <h2>Card Sets</h2>
                <div>
                  {sets &&
                    sets.map((set) => (
                      <Link
                        href={`/${set.id}`}
                        key={set.id}
                        className={`px-4 py-2 rounded cursor-pointer flex flex-col ${
                          params.id === set.id && "bg-gray-800"
                        }`}
                      >
                        {set.title}
                      </Link>
                    ))}
                </div>
              </div>
            </div>

            <Provider store={store}>
              <div className="flex-1">{children}</div>
            </Provider>
          </main>
        </div>
      </body>
    </html>
  );
}
